[profile.default]
names = true
sizes = true
via-ir = false
libs = ["node_modules", "lib"]
fs_permissions = [
    { access = "read", path = "./broadcast/DeployMorpho.sol/"},
    { access = "read", path = "./script/config/"},
    { access = "read", path = "./lib/morpho-blue/out/"},
    { access = "read", path = "./lib/morpho-blue-irm/out/"},
    { access = "read", path = "./lib/morpho-blue-oracles/out/"},
    { access = "read", path = "./lib/morpho-blue-bundlers/out/"},
    { access = "read", path = "./lib/metamorpho/out/"}
]

[profile.default.fmt]
wrap_comments = true

[profile.default.rpc_endpoints]
ethereum = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
tenderly = "https://rpc.tenderly.co/fork/${TENDERLY_FORK_ID}"


[profile.test]
ffi = true
via-ir = false


[profile.script]
test = "/dev/null"


# See more config options https://github.com/foundry-rs/foundry/tree/master/crates/config
